version: '3.4'
services:
        evote:
                build:
                        context: Evote_Service
                container_name: evote
                ports:
                        - "98:80"
                volumes:
                        - /home/cnoc/logsEvoteService:/app/logs
                        - /home/cnoc/uploadphotoid:/app/uploadphotoid
                        - /home/cnoc/uploadkyc:/app/uploadkyc
                        - /home/cnoc/uploadface:/app/uploadface
                restart: always
                env_file:
                        - .env
                environment:
                        - TZ=Asia/Bangkok


